### ISSUE TITLE
SO-version needs to be incremented

### ISSUE THREAD

**Issue by susnux** [Matroska-Org/libmatroska#10]
I think the so-version should be incremented,  because a so version of 6 means that libmatroska.so.6 is abi compatible to all libmatroska.so.6.* but with the last change this is not true anymore.

Problem I had:
I have built mkvtoolnix 9.3.1 which requires 1.4.5, but then after installing the mkvtoolnix package mkvtoolnix requires only libmatroska.so.6 but the system-one (1.4.4) does not provide the symbol:

    _ZN11libmatroska14KaxVideoColour10ClassInfosE

And if I understand this gnu guideline correctly:
https://www.gnu.org/software/libtool/manual/html_node/Updating-version-info.html
After adding this new interface the "current" should be incremented.

**Comment by mbunkus** [comment]
I'm pretty sure you misunderstand the term "ABI-compatiible". This usually means that if an application is linked against an older version of a library (e.g. Qt 5.2) it will still work if the system has a newer version of the library installed (e.g. Qt 5.6).

Your situation is different. MKVToolNix requires a newer version of the library than you have installed. It is currently linked against a newer version (v1.4.5), but that doesn't mean that it'll work with older versions of library (1.4.4 in your case). If you only had v1.4.4 installed during compilation then MKVToolNix wouldn't even have compiled (more correctly: it would have used its own internal copy of libmatroska and linked that statically).

Adding new features to a library does NOT always break ABI compatibility. It can, depending on the kind of features added and how they were added. For example, adding a new virtual method in an existing class before an already existing other virtual method will break ABI compatibility. However, libMatroska v1.4.5 only added whole new classes, and that does not break ABI compatibility.

libMatroska does not use libtool's version scheme, nor does it follow the semantic versioning scheme. Therefore the link you've posted doesn't apply either.

**Comment by mbunkus** [comment]
If in doubt you should always refer to [these excellent guidelines for ABI compatibility for C++](https://community.kde.org/Policies/Binary_Compatibility_Issues_With_C%2B%2B#The_Do.27s_and_Don.27ts) by the KDE project. Adding new classes is listed as being OK. I'm therefore closing this.

**Comment by susnux** [comment]
So the so version only ensures downwards compatibility? Ok then I have to fix this dependency manually for the package.
