### ISSUE TITLE
Critical issue with the "French" language flag

### ISSUE THREAD

**Issue by gravelfreeman** [Matroska-Org/libmatroska#110]
I'm a French Canadian who've been working with MKV files since they're out and I can tell that the French language flag needs to be updated to take into consideration the Canadian French language. Most of the movies since the 90's are dubbed in French in the province of Quebec. It's really hard to distinguish between the 3 categories of french language. From my knowledge there are 3 main categories.

1. International French also known as VFI
2. French also known as Truefrench or VFF
3. French Canadian also known as VFQ

When remuxing a bluray that has both french language there wont have any distinction between them unless you write a custom audio track name. This has been an issue for years on streaming services like Amazon and also on P2P sharing communities. It would be great to standardize this so we could use the custom track name for describing the audio format which is how I understand MKV was meant to do it originally.

**Comment by gravelfreeman** [comment]
Hi, you're right they're supported and I already seen them but is it possible that the majority of the main players are ignoring it? Or I may have done something wrong.

For example this is the MKV header for Inception of my blu-ray remux in mkvtoolnix I've setup;

![image](https://github.com/Matroska-Org/libmatroska/assets/44218371/34148b96-5708-48a7-99ba-505612ef1613)

Then if I check in MediaInfo it seems to be ignoring the BCP47 field

`Audio #2
ID                                       : 3
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : A_AAC-2
Duration                                 : 2 h 28 min
Bit rate                                 : 128 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 46.875 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 135 MiB (0%)
Title                                    : Stereo
Language                                 : French
Default                                  : No
Forced                                   : No`

Same thing in Plex

![image](https://github.com/Matroska-Org/libmatroska/assets/44218371/fcd7b165-cecd-4659-9231-5493736a12a0)

Same thing in VLC

![image](https://github.com/Matroska-Org/libmatroska/assets/44218371/875dfe30-7481-45e9-a05a-5171bd24648b)

Hope this gets supported soon.

**Comment by mbunkus** [comment]
Again, this isn't a bug in libmatroska. File bug reports with the actual software that produces files or reads files & that doesn't handle those languages correctly.
