### ISSUE TITLE
question

### ISSUE THREAD

**Issue by publicocean0** [Matroska-Org/libmatroska#12]
i can not find a file where there is the association codec matroska --> codec mse 
https://www.matroska.org/technical/specs/codecid/index.html
Examples of valid MIME-types with a codecs parameter.

audio/webm;codecs="vorbis"
video/webm;codecs="vorbis"
video/webm;codecs="vp8"
video/webm;codecs="vp8,vorbis"
video/webm;codecs="vp9,opus"

**Comment by mbunkus** [comment]
Such questions are outside the scope of a bug tracker. They're better suited for mailing lists such as the [IETF's CELLAR project mailing list](https://www.ietf.org/mailman/listinfo/cellar) or the [Matroska-devel](https://lists.matroska.org/cgi-bin/mailman/listinfo) mailing list.
