### ISSUE TITLE
Allow libebml to be brought in as a source dependency

### ISSUE THREAD

**Issue by schultetwin1** [Matroska-Org/libmatroska#18]
Currently, we are unable to build libmatroska and libebml in the same cmake "superbuild". In https://github.com/schultetwin1/libmatroska/blob/2cf0198cf3df9ced38c27fac9d45bea4fe8fd74f/CMakeLists.txt#L8-L9 CMAKE_MODULE_PATH is set to a non-existent path and then requires Ebml to be found via find_package. This means Ebml must be installed on your machine.

In our use case we have directories laid out in the following way:
/src
/extern
  CMakeLists.txt
  /ebml
    CMakeLists.txt
    ... (The rest of the ebml code)
  /matroska
    CMakeLists.txt
    ... (The rest of the matroska code)

Since we are pulling in ebml by source and building it, we are able to build matroska without find_package working. However, we are unable to do so because find_package will currently always fail in this situation.

My solution is to not override CMAKE_MODULE_PATH. So that in our super build we can define an empty FindEbml.config file and be on our way.

**Comment by mbunkus** [comment]
As #19 was merged quite a while ago, I'm closing this issue.
