### ISSUE TITLE
Linking against libmatroska.dll (lib) fails 

### ISSUE THREAD

**Issue by Maturin** [Matroska-Org/libmatroska#35]
After building libebml and libmatroska on Windows using Visual Studio 2015, building an application, in this case an unit test, fails with unresolved dependencies like these:

    ... : error LNK2001: unresolved external symbol "public: static class libebml::EbmlCallbacks const libmatroska::KaxSeekHead::ClassInfos" (?ClassInfos@KaxSeekHead@libmatroska@@2VEbmlCallbacks@libebml@@B)
    ... : error LNK2001: unresolved external symbol "public: static class libebml::EbmlCallbacks const libmatroska::KaxInfo::ClassInfos" (?ClassInfos@KaxInfo@libmatroska@@2VEbmlCallbacks@libebml@@B)
    ... <several more of these errors> 
    ... : error LNK2001: unresolved external symbol "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const libmatroska::KaxCodeVersion" (?KaxCodeVersion@libmatroska@@3V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@B)

After investigating these problem I figured out two problems:

1.) The MATROSKA_DLL_API is set to nothing, when the libmatroska header file are included in my project.
2.) The KaxCodeVersion variable is not exported

Right now I am preparing a pull request for solving these link problem.

**Comment by mbunkus** [comment]
As #36 was merged quite a while ago, I'm closing this issue.
