### ISSUE TITLE
Drop MATROSKA_VERSION define 

### ISSUE THREAD

**Issue by robUx4** [Matroska-Org/libmatroska#41]
The only use is to be able to build the library to parse only Matroska version 1 elements. This has no use for pretty much anyone, and it's a pain to generate the code correctly.

In libmatroska2 all elements are supported in each build but marked for which version of Matroska/WebM/DivX they are allowed.

The selection of what subset you want should be done at runtime, not compilation time. Compiling with just just v1 elements won't make the code much smaller.

It shouldn't break ABI or API as it only adds classes for those (rare) people who only wanted v1 classes.

**Comment by mbunkus** [comment]
`libmatroska` allows for other people to define `MATROSKA_VERSION` and only defines it itself if it isn't defined yet. This means that simply removing will break the ABI for people who did define it to be `< 2`.

Additionally the removal will break the API for any source code checking its value. MKVToolNix used to do this. It doesn't anymore, though.

Yeah, the number of people actually defining it beforehand is probably 0. The number of projects checking its value is potentially higher than 0, though.

I'm not against dropping it, but we should err on the side of caution & explicitly state that such a release will break API & ABI under certain conditions. And bunch the other pending, ABI-breaking PRs in such a release.

**Comment by robUx4** [comment]
I don't think it qualifies as an ABI "breakage" if you add new ABI entries but the old ones are unchanged.

I do agree on the API breakage for the define. I was planning to add an `#error` if it's defined externally to something smaller than 2. So that code that might have used the feature will notice for sure. It's probably a good idea to keep the define to 2 for legacy reasons, as you mentioned.

**Comment by JackBoosY** [comment]
This breaks the latest version of azure-kinect-sensor-sdk.

**Comment by robUx4** [comment]
Can you point to some error logs ? It should not be hard to fix.

**Comment by JackBoosY** [comment]
@robUx4 
`    28>D:\buildtrees\azure-kinect-sensor-sdk\src\.0-alpha.0-30d96b3859.clean\src\record\sdk\record.cpp(543,59): error C2065: 'MATROSKA_VERSION': undeclared identifier [D:\buildtrees\azure-kinect-sensor-sdk\x64-windows-dbg\src\record\sdk\k4arecord.vcxproj]`

**Comment by robUx4** [comment]
If this [is this thing](https://docs.microsoft.com/en-us/azure/kinect-dk/sensor-sdk-download), it seems to be an error in the packages. The new libmatroska package in your distro should not be mark it as compatible with older versions.
Now, that being said, we thought noone was using this so we are probably the ones to blame.

It's probably [this line](https://github.com/microsoft/Azure-Kinect-Sensor-SDK/blob/a227f73b8c78e17db843e7a962a1fabd571c6213/src/record/sdk/record.cpp#L546) that needs a fix. I'll submit a patch.
