### ISSUE TITLE
matroska build dll visual studio

### ISSUE THREAD

**Issue by israelariel** [Matroska-Org/libmatroska#6]
I am writting here because i just cannot find the solution of how to built libmatroska dll's library with visual studio 2005 and google didn't help this time. If this is not the place to ask forgive me  and please indicate me where to. I downloaded the code form the source at Git's repo. I First thing was to open the project in make/vc7/ folder then delete from project file included but not existing as KaxChapters.cpp, KaxClusterData.cpp etc... The projetc include projects: libebml, libebmldll, libmatroska, libmatroskadll and others test related. The first 3 compile just fine after remove the non-existing files and adding the dependences at properties->Reference o the selected project. The code of libmatroskadll error at linking process. Any help is appreciated. I obtained about 5000 error similar to the nexts:

```
    Linking...
```

1>   Creating library Debug/libmatroska.lib and object Debug/libmatroska.exp
1>KaxInfoData.obj : error LNK2001: unresolved external symbol "public: static class libebml::EbmlCallbacks const libmatroska::KaxSeekID::ClassInfos" (?ClassInfos@KaxSeekID@libmatroska@@2VEbmlCallbacks@libebml@@B)
1>KaxSeekHead.obj : error LNK2001: unresolved external symbol "public: static class libebml::EbmlCallbacks const libmatroska::KaxSeekID::ClassInfos" (?ClassInfos@KaxSeekID@libmatroska@@2VEbmlCallbacks@libebml@@B)
1>KaxSegment.obj : error LNK2001: unresolved external symbol "public: static class libebml::EbmlCallbacks const libmatroska::KaxSeekID::ClassInfos" (?ClassInfos@KaxSeekID@libmatroska@@2VEbmlCallbacks@libebml@@B)

**Comment by israelariel** [comment]
well seem to me that visual studio compilation is unsuported, but dll also is? Sorry if these is a dummy question. Now i using Dev c++ and libebml's dll building also fails:

../../src/EbmlCrc32.o:EbmlCrc32.cpp:(.text+0x15d): undefined reference to `libebml::MemIOCallback::MemIOCallback(unsigned long long)'
../../src/EbmlCrc32.o:EbmlCrc32.cpp:(.text+0x1b6): undefined reference to `libebml::MemIOCallback::~MemIOCallback()'
../../src/EbmlCrc32.o:EbmlCrc32.cpp:(.text+0x1c7): undefined reference to `libebml::MemIOCallback::~MemIOCallback()'
../../src/EbmlCrc32.o:EbmlCrc32.cpp:(.text+0x203): undefined reference to `libebml::MemIOCallback::MemIOCallback(unsigned long long)'
../../src/EbmlCrc32.o:EbmlCrc32.cpp:(.text+0x263): undefined reference to `libebml::MemIOCallback::~MemIOCallback()'
../../src/EbmlCrc32.o:EbmlCrc32.cpp:(.text+0x276): undefined reference to `libebml::MemIOCallback::~MemIOCallback()'
c:/program files (x86)/dev-cpp/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.8.1/../../../../x86_64-w64-mingw32/bin/ld.exe: ../../src/EbmlCrc32.o: bad reloc address 0x0 in section `.pdata$_ZN7libebml6EbmlIdC1Ejj'
collect2.exe: error: ld returned 1 exit status

C:\Source Libs\libebml\make\mingw32\Makefile.win:28: recipe for target 'libebml.dll' failed
mingw32-make.exe: *** [libebml.dll] Error 1

I am c++ entusiast, hoping use and help with matroska libs

**Comment by mbunkus** [comment]
We don't support Visual C at the moment anymore due to lack of developers actually using Visual C. Sorry.
