### ISSUE TITLE
new release soon?

### ISSUE THREAD

**Issue by mbunkus** [Matroska-Org/libmatroska#70]
@robUx4 I'd like to make new releases of libEBML & libMatroska soon in order to be able to start supporting the new elements in MKVToolNix. Do you plan to add any more things soon?

The only thing left for me to merge is #66 . I'm also aware of ietf-wg-cellar/matroska-specification#670 which we should probably include in the release. Anything else?

**Comment by mbunkus** [comment]
TODO/blocker list:

[ ] verify & merge #66 
[ ] integrate ietf-wg-cellar/matroska-specification#670 into libmatroska
[ ] fix ietf-wg-cellar/matroska-specification#672 & integrate into libMatroska

**Comment by robUx4** [comment]
Apart from update the files files once the Emphasis ID is fixed, I don't plan to add anything more.

**Comment by neheb** [comment]
New release would be great to fix GCC > 10 compilation

**Comment by mbunkus** [comment]
I am on it. Will likely release both libraries tomorrow.

**Comment by mbunkus** [comment]
I was just in the middle of doing the releases for both libraries, but it seems there's still too much discussion going on over all three relevant repositories. I had already pushed the release tag for libEBML, which I've now removed again. We can adjust the release date in `NEWS.md` when the actual release is done.

So let's wait a couple of days before doing the actual releases — there's no urgent need to get them out today.

**Comment by robUx4** [comment]
BTW, the library does build with GCC10: https://github.com/Matroska-Org/libmatroska/actions/workflows/linux-gcc10.yaml (and so does libebml)

**Comment by mbunkus** [comment]
It does, yes, also with gcc 11 & 12 which I use as my primary driver, but for libEBML this is only true since commit [f0bfd53647961e799a43d918c46cf3b6bff89806 ](https://github.com/Matroska-Org/libebml/commit/f0bfd53647961e799a43d918c46cf3b6bff89806), which isn't part of a release yet — hence @neheb being eager for the new release.

**Comment by mbunkus** [comment]
The new releases are [out now](https://www.matroska.org/downloads/libraries.html).
