### ISSUE TITLE
Fix -DEbml_DIR=/path/to/libebml in the README

### ISSUE THREAD

**Issue by robUx4** [Matroska-Org/libmatroska#73]
The `Ebml_DIR` option mention in the `README.md` doesn't exist and is ignored. I'm not sure what it the correct way to signal this (some combination of CMAKE_MODULE_PATH probably).

**Comment by mbunkus** [comment]
It's called `EBML_DIR` and works, but you often would rather use `CMAKE_INSTALL_PREFIX`.

For example, if you build & install libEBML like this:

```
cmake -DCMAKE_INSTALL_PREFIX=$HOME/opt/ebmlmatroska -DBUILD_SHARED_LIBS=no ..
```

you'll likely want to install libMatroska into the same directory, hence:

```
cmake -DCMAKE_INSTALL_PREFIX=$HOME/opt/ebmlmatroska -DBUILD_SHARED_LIBS=no ..
```

That suffices for both detection & setting the target directory.

However, this also compiles, but still installs in the default directory:

```
cmake -DEBML_DIR=$HOME/opt/ebmlmatroska/lib/cmake/EBML -DBUILD_SHARED_LIBS=no ..
```

**Comment by robUx4** [comment]
Indeed, it works when not setting `CMAKE_INSTALL_PREFIX`, otherwise it warns that the Ebml_DIR parameters has not been used.
