### ISSUE TITLE
no such file or directory: ./configure

### ISSUE THREAD

**Issue by amilajack** [Matroska-Org/libmatroska#9]
I'm not a C++ developer but i'm trying to compile this project. I'm getting the error:
```
no such file or directory: ./configure
```
 when running `./configure` inside a directory that I downloaded from the releases page. Is there something wrong with what I'm doing?

**Comment by mbunkus** [comment]
You've probably downloaded from github. That's not an official release, that's just a snapshot from the Git repository. Please download official releases from [the official www.matroska.org download site](https://www.matroska.org/downloads/windows.html). Those archives do contain `configure`.

If you want to use Git sources (nothing wrong with that) then you need to run `libtoolize` followed by `autoreconf -vi`. That'll create `configure`. See the [README.md file](https://github.com/Matroska-Org/libmatroska/blob/master/README.md) I've just created yesterday.
